
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.btc4j.ws;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-01-23T06:18:59.218-06:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "$service.ServiceName",
                      targetNamespace = "$service.Namespace",
                      wsdlLocation = "file:/E:/eclipse/workspace/btc4j-ws/src/main/resources/btc4j-ws.wsdl",
                      endpointInterface = "org.btc4j.ws.BtcDaemonServicePort")
                      
public class BtcDaemonServicePortImpl implements BtcDaemonServicePort {

    private static final Logger LOG = Logger.getLogger(BtcDaemonServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.btc4j.ws.BtcDaemonServicePort#help(org.btc4j.ws.HelpReq  params )*
     */
    public org.btc4j.ws.HelpResp help(HelpReq params) throws BtcException    { 
        LOG.info("Executing operation help");
        System.out.println(params);
        try {
            org.btc4j.ws.HelpResp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new BtcException("btcException...");
    }

}
