package org.btc4j.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-01-23T06:18:59.234-06:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://www.btc4j.org/ws/", name = "BtcDaemonServicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BtcDaemonServicePort {

    @WebResult(name = "helpResp", targetNamespace = "http://www.btc4j.org/ws/", partName = "params")
    @WebMethod
    public HelpResp help(
        @WebParam(partName = "params", name = "helpReq", targetNamespace = "http://www.btc4j.org/ws/")
        HelpReq params
    ) throws BtcException;
}
