
package org.btc4j.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-01-23T06:18:59.218-06:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "btcFault", targetNamespace = "http://www.btc4j.org/ws/")
public class BtcException extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 4373962760283171604L;
	private org.btc4j.ws.BtcFault btcFault;

    public BtcException() {
        super();
    }
    
    public BtcException(String message) {
        super(message);
    }
    
    public BtcException(String message, Throwable cause) {
        super(message, cause);
    }

    public BtcException(String message, org.btc4j.ws.BtcFault btcFault) {
        super(message);
        this.btcFault = btcFault;
    }

    public BtcException(String message, org.btc4j.ws.BtcFault btcFault, Throwable cause) {
        super(message, cause);
        this.btcFault = btcFault;
    }

    public org.btc4j.ws.BtcFault getFaultInfo() {
        return this.btcFault;
    }
}
